---

- name: Zookeeper configuration
  copy:
    content: |
      dataDir=/var/zookeeper/data
      clientPort={{ zookeeper_port }}
      maxClientCnxns=0
      dataLogDir=/var/log/zookeeper/
    dest: /etc/zookeeper/server.properties
  notify: Restart Zookeeper

- name: Create Zookeeper SystemD unit configuration
  copy:
    content: |
      [Unit]
        Description=ZooKeeper Service
        Documentation=http://zookeeper.apache.org
        Requires=network.target
        After=network.target

      [Service]
        User=kafka
      #  Group=zookeeper
        ExecStart=/usr/lib/kafka/bin/zookeeper-server-start.sh /etc/zookeeper/server.properties

      [Install]
        WantedBy=default.target
    dest: /etc/systemd/system/zookeeper.service
  notify: Restart Zookeeper

- name: Enable Zookeeper service
  service:
    name: "zookeeper"
    enabled: yes
    state: started
