---

- name: Zookeeper MyID file
  copy:
    content: |
      {{ zookeeper_id }}
    dest: /var/zookeeper/data/myid
  notify: Restart Zookeeper

- name: Zookeeper configuration
  copy:
    content: |
      dataDir=/var/zookeeper/data
      clientPort={{ zookeeper_port }}
      clientPortAddress={{ ansible_default_ipv4['address'] }}
      maxClientCnxns=0
      tickTime=2000
      initLimit=5
      syncLimit=2
      {% for host in groups['zookeepers'] %}
      {% if 'ansible_default_ipv4' in hostvars[host] %}
      server.{{ hostvars[host]['zookeeper_id'] }}={{ hostvars[host]['ansible_default_ipv4']['address'] }}:2888:3888
      {% endif %}
      {% endfor %}
    dest: /etc/zookeeper/server.properties
  notify: Restart Zookeeper

- name: Create Zookeeper SystemD unit configuration
  copy:
    content: |
      [Unit]
        Description=ZooKeeper Service
        Documentation=http://zookeeper.apache.org
        Requires=network.target
        After=network.target

      [Service]
        Environment=LOG_DIR=/var/log/zookeeper/
        User=kafka
      #  Group=zookeeper
        ExecStart=/usr/lib/kafka/bin/zookeeper-server-start.sh /etc/zookeeper/server.properties

      [Install]
        WantedBy=default.target
    dest: /etc/systemd/system/zookeeper.service
  notify: Restart Zookeeper

- name: Enable Zookeeper service
  service:
    name: "zookeeper"
    enabled: yes
    state: started
