---

- name: install JDK via yum
  yum:
    name: "{{ java_zulu_mirror }}/zulu{{ java_version }}.{{ java_zulu_build }}-jdk{{ java_version }}-linux.x86_64.rpm"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: install JDK via apt
  apt:
    deb: "{{ java_zulu_mirror }}/zulu{{ java_version }}.{{ java_zulu_build }}-jdk{{ java_version }}-linux_amd64.deb"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
