---
- user:
    name: kafka

- name: Install Kafka
  unarchive:
    src: "{{ kafka_mirror }}/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
    dest: /usr/lib/
    remote_src: yes

- name: Link kafka
  file:
    src: "/usr/lib/kafka_{{ kafka_scala_version }}-{{ kafka_version }}"
    dest: /usr/lib/kafka
    state: link
    owner: kafka

- name: Create config directories
  file:
    path: "/etc/{{ item }}"
    state: directory
  with_items:
    - kafka
    - zookeeper

- name: Create log directories
  file:
    path: "/var/log/{{ item }}"
    state: directory
    owner: kafka
  with_items:
    - kafka
    - zookeeper

- name: Create data directories
  file:
    path: "/var/{{ item }}/data"
    state: directory
    owner: kafka
  with_items:
    - kafka
    - zookeeper
